#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THIS_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(THIS_FILE), '..');
const INDEX_PATH = path.join(ROOT, 'works/index.json');
const SITE_URL = 'https://gpt-image-2-hub-seven.vercel.app';
const TIERS = [9, 6, 3];

const BADGES_EN = [
  '![GPT Image 2](https://img.shields.io/badge/model-GPT--Image--2-10a37f?logo=openai&logoColor=white)',
  '![Works](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FChaosRealmsAI%2Fgpt-image-2-hub%2Fmain%2Fworks%2Findex.json&query=%24.stats.image_count&label=works&color=blue)',
  '![License](https://img.shields.io/badge/license-MIT-green)',
  '![Live Site](https://img.shields.io/badge/live-vercel-black?logo=vercel)',
].join(' ');

const STR = {
  en: {
    title: 'GPT Image 2 Hub · AI Image Inspiration Atlas',
    tagline: 'A curated atlas of **GPT-Image-2** (ChatGPT Images 2.0 · OpenAI · released 2026-04-21) generations. Every work ships with its full prompt — copy and remix.',
    stats: (t, p, i) => `**${t} topics · ${p} packages · ${i} works**`,
    langToggle: '[简体中文](./README.zh-CN.md)',
    badges: BADGES_EN,
    geoHeader: (t, p, i) => `## What is GPT Image 2 Hub?

**GPT Image 2 Hub** is a public atlas of prompts for **GPT-Image-2** — OpenAI's next-generation image model released on **April 21, 2026** (also called **ChatGPT Images 2.0**, powered by the GPT-5.4 backbone). This repository catalogs **${i} curated works** across **${t} themes** and **${p} packages**, every generation paired with its full copy-paste prompt so the output can be reproduced or remixed directly.

## Who it's for

- **Designers & illustrators** — reproducible style references across 10 visual categories
- **Prompt engineers** — multilingual text rendering, layout control, style anchoring
- **Content creators** — posters, covers, infographics, editorial imagery at scale
- **Researchers** — benchmarking GPT-Image-2 against specific creative constraints

## How to use

1. Browse by **category** (typography, illustration, photography…) or by **theme** (fictional symbol systems, multi-script posters…).
2. Click any work to open the live page — it includes the **full prompt in English and Chinese**.
3. Copy the prompt into ChatGPT Images 2.0 · reproduce, tweak, remix.
4. Licensed MIT — prompts are free to ship commercially.
`,
    faq: `## FAQ

**What is GPT Image 2 / gpt-image-2 / ChatGPT Images 2.0?**
Three names for the same model: OpenAI's next-generation image generation model released on **April 21, 2026**. It renders text with ~99% accuracy across Latin, Japanese, Korean, Chinese, Hindi, and Bengali scripts; outputs up to **4096×4096**; and runs roughly 2× faster than its predecessor. Natively integrated into ChatGPT on the GPT-5.4 backbone.

**What makes this atlas different from a random prompt dump?**
Every entry is curated, reproducible, and localized (EN + 简体中文). Themes are versioned by stable slug; works inside a theme share a controlled design language so style transfer is explicit rather than accidental.

**Can I reuse the prompts commercially?**
Yes — repository code and prompt text are MIT licensed.

**How is the content organized?**
Themes → packages → works. A **theme** (e.g. \`fictional-symbol-system\`) groups **packages** (series studies or single explorations), and each package lists individual **works** with full metadata (title, description, alt text, prompt, bilingual labels).

**How do I reproduce a specific work?**
Open its live page, copy either the English or Chinese prompt verbatim into ChatGPT Images 2.0, and run. Outputs vary slightly between runs — that is expected.

**How often is the atlas updated?**
Continuously. New themes are added weekly; existing themes are expanded as new visual patterns emerge in GPT-Image-2.
`,
    footer: 'Generated by `npm run readme:gen` · [llms.txt](https://gpt-image-2-hub-seven.vercel.app/llms.txt) for AI indexers',
  },
  'zh-CN': {
    title: 'GPT Image 2 Hub · AI 视觉灵感图鉴',
    tagline: '一份精选的 **GPT-Image-2**(ChatGPT Images 2.0 · OpenAI · 2026-04-21 发布)作品集 · 每张图都附完整提示词 · 可直接复制复用。',
    stats: (t, p, i) => `**${t} 主题 · ${p} 合集 · ${i} 作品**`,
    langToggle: '[English](./README.md)',
    badges: BADGES_EN,
    geoHeader: (t, p, i) => `## 这是什么?

**GPT Image 2 Hub** 是一份面向 **GPT-Image-2**(OpenAI 于 **2026 年 4 月 21 日** 发布的新一代图像模型 · 又名 **ChatGPT Images 2.0** · 底座 GPT-5.4)的公开提示词图鉴。仓库收录 **${i} 张** 精选作品 · 覆盖 **${t} 个主题** 和 **${p} 个合集** · 每张图都附完整可复制提示词 · 一键复刻或二创。

## 给谁用

- **设计师与插画师** — 风格可复现的参考库,覆盖 10 大视觉分类
- **提示词工程师** — 多语言文字渲染、布局控制、风格锚定研究
- **内容创作者** — 批量产海报、封面、信息图、编辑配图
- **研究者** — 测试 GPT-Image-2 在特定创作约束下的表现

## 怎么用

1. 按 **分类** 浏览(文字、插画、摄影...)或按 **主题** 浏览(虚构符号系统、多文种海报...)。
2. 点任意作品进入详情页 · 里面有 **中英双语完整提示词**。
3. 把提示词粘贴到 ChatGPT Images 2.0 · 复刻、调整、二创。
4. MIT 许可 · 提示词可直接商用。
`,
    faq: `## 常见问题

**GPT Image 2 / gpt-image-2 / ChatGPT Images 2.0 是啥?**
三个名字指同一个模型:OpenAI 于 **2026 年 4 月 21 日** 发布的新一代图像生成模型。拉丁、日、韩、中、印地、孟加拉文字渲染准确率约 **99%**;最高分辨率 **4096×4096**;速度约为前代 2 倍。原生集成于 ChatGPT · 底座 GPT-5.4。

**这个图鉴跟随便丢一堆提示词有啥不同?**
每条都经过精选、可复现、双语化(EN + 简体中文)。主题按稳定 slug 版本化;同主题下的作品共享一套可控的设计语言 · 风格迁移是显式的不是意外的。

**提示词可以商用吗?**
可以。仓库代码和提示词文本是 MIT 许可。

**内容怎么组织?**
主题 → 合集 → 作品。一个 **主题**(如 \`fictional-symbol-system\`)下分 **合集**(系列研究或单品探索) · 每个合集下列 **作品** 及其完整元数据(标题 / 描述 / alt 文字 / 提示词 / 中英标签)。

**怎么复刻某张图?**
打开它的详情页 · 把中英任一版提示词原样粘贴到 ChatGPT Images 2.0 运行即可。每次生成略有差异 · 属正常现象。

**图鉴多久更新一次?**
持续更新。每周新增主题;已有主题随新视觉模式持续扩展。
`,
    footer: '由 `npm run readme:gen` 自动生成 · [llms.txt](https://gpt-image-2-hub-seven.vercel.app/llms.txt) 面向 AI 索引器',
  },
};

function readIndex() {
  return JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
}

function variantUrl(imagePath) {
  const noExt = String(imagePath).replace(/\.(png|jpg|jpeg|webp)$/i, '');
  return `./${noExt.replace(/^\.?\//, '')}.w400.webp`;
}

function localized(obj, field, lang) {
  return obj?.i18n?.[lang]?.[field]
    || obj?.i18n?.en?.[field]
    || obj?.i18n?.['zh-CN']?.[field]
    || obj?.[field]
    || '';
}

function escapeHtml(str) {
  return String(str).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

function topicHref(topicId) {
  return `${SITE_URL}/#t-${encodeURIComponent(topicId)}`;
}

function imageHref(imageId) {
  return `${SITE_URL}/#m-${encodeURIComponent(imageId)}`;
}

function tierLimit(count) {
  return TIERS.find((n) => count >= n) ?? 0;
}

function sortTopics(a, b) {
  const ao = Number(a.display?.sort_order ?? Number.POSITIVE_INFINITY);
  const bo = Number(b.display?.sort_order ?? Number.POSITIVE_INFINITY);
  if (ao !== bo) return ao - bo;
  return localized(a, 'title', 'en').localeCompare(localized(b, 'title', 'en'));
}

function render(lang) {
  const idx = readIndex();
  const s = STR[lang];
  const topics = idx.topics || [];
  const categoryDefs = idx.categories?.category || {};
  const categoryOrder = Object.keys(categoryDefs);
  const imagesByTopic = new Map();
  for (const img of idx.images || []) {
    if (!imagesByTopic.has(img.topic_id)) imagesByTopic.set(img.topic_id, []);
    imagesByTopic.get(img.topic_id).push(img);
  }

  const topicCount = idx.stats?.topic_count || 0;
  const packageCount = idx.stats?.package_count || 0;
  const imageCount = idx.stats?.image_count || 0;

  const lines = [];
  lines.push(`# ${s.title}`);
  lines.push('');
  lines.push(s.badges);
  lines.push('');
  lines.push(`${s.tagline}`);
  lines.push('');
  lines.push(`${s.stats(topicCount, packageCount, imageCount)} · ${s.langToggle}`);
  lines.push('');
  lines.push(s.geoHeader(topicCount, packageCount, imageCount));
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(lang === 'zh-CN' ? '## 按分类浏览' : '## Browse by category');
  lines.push('');

  const topicsWithImages = topics.filter((t) => tierLimit((imagesByTopic.get(t.id) || []).length) > 0);
  const topicsByCategory = new Map();
  for (const topic of topicsWithImages) {
    const categoryId = topic.category || 'illustration';
    if (!topicsByCategory.has(categoryId)) topicsByCategory.set(categoryId, []);
    topicsByCategory.get(categoryId).push(topic);
  }

  for (const categoryId of categoryOrder) {
    const categoryTopics = (topicsByCategory.get(categoryId) || []).slice().sort(sortTopics);
    if (!categoryTopics.length) continue;

    const category = categoryDefs[categoryId] || {};
    const categoryLabel = category.labels?.[lang]
      || category.labels?.en
      || categoryId;
    const icon = category.icon || '';

    lines.push(`## ${icon} ${categoryLabel}`.trim());
    lines.push('');

    for (const topic of categoryTopics) {
      const topicTitle = localized(topic, 'title', lang);
      const topicDesc = localized(topic, 'description', lang);
      const originalCount = (imagesByTopic.get(topic.id) || []).length;
      const imgs = (imagesByTopic.get(topic.id) || [])
        .slice()
        .sort((a, b) => {
          const ao = Number(a.generation?.order ?? 0);
          const bo = Number(b.generation?.order ?? 0);
          return ao - bo || String(a.id).localeCompare(String(b.id));
        })
        .slice(0, tierLimit(originalCount));

      lines.push(`### [${topicTitle}](${topicHref(topic.id)}) · ${originalCount}`);
      lines.push('');
      if (topicDesc) {
        lines.push(`> ${topicDesc}`);
        lines.push('');
      }

      lines.push('<table>');
      for (let i = 0; i < imgs.length; i += 3) {
        lines.push('<tr>');
        for (let j = i; j < i + 3; j += 1) {
          if (j >= imgs.length) {
            lines.push('<td width="33%"></td>');
            continue;
          }
          const img = imgs[j];
          const imgTitle = localized(img, 'title', lang) || img.id;
          const imgUrl = variantUrl(img.image);
          const liveImageHref = imageHref(img.id);
          const alt = img.display?.alt?.[lang]
            || img.display?.alt?.en
            || img.display?.alt?.['zh-CN']
            || imgTitle;
          lines.push('<td width="33%" valign="top" align="center">');
          lines.push('');
          lines.push(`<a href="${liveImageHref}"><img src="${imgUrl}" width="220" alt="${escapeHtml(alt)}"/></a>`);
          lines.push('');
          lines.push(`<b><a href="${liveImageHref}">${escapeHtml(imgTitle)}</a></b>`);
          lines.push('');
          lines.push('</td>');
        }
        lines.push('</tr>');
      }
      lines.push('</table>');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(s.faq);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`<sub>${s.footer}</sub>`);
  lines.push('');

  return lines.join('\n');
}

const outputs = [
  { file: 'README.md', lang: 'en' },
  { file: 'README.zh-CN.md', lang: 'zh-CN' },
];

for (const { file, lang } of outputs) {
  const md = render(lang);
  fs.writeFileSync(path.join(ROOT, file), md);
  console.log(`wrote ${file} (${md.length} chars · ${lang})`);
}
